# Generated by Django 3.1.7 on 2021-06-30 09:42

from django.conf import settings
from django.db import migrations, models
import mp_database_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp_database_app', '0004_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET(mp_database_app.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET(mp_database_app.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET(mp_database_app.models.get_deleted_user_instance), to=settings.AUTH_USER_MODEL),
        ),
    ]
