# Generated by Django 3.1.7 on 2021-06-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_database_app', '0005_auto_20210630_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
