# Generated by Django 3.1.7 on 2021-06-30 20:50

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mp_database_app', '0006_recipe_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
