# Generated by Django 3.1.7 on 2021-06-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_database_app', '0007_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
