# Generated by Django 3.1.7 on 2021-07-01 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_database_app', '0010_auto_20210701_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='hours',
            new_name='chours',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='minutes',
            new_name='cminutes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='preparation_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='phours',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pminutes',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)]),
        ),
    ]
